### ISSUE TITLE
Sign out Issue

### ISSUE THREAD

**Issue by ashok385** [TallaBotChain/botchain-example-service#19]
When I hit Sign Out and press the back button, the session seems to be still active. 
![image](https://user-images.githubusercontent.com/44645170/47872298-8cd74400-dde4-11e8-91cc-8e0882b3208e.png)

In essence , it should force me to signup again.

**Comment by server-izetov** [comment]
This issue id not actual now. But we have issue with SignOut from wallet or products pages, after hit SignOut and press back button we catch Routing Error. I've prepared fix for this issue
